sonar.issue.ignore.multicriteria=dockerBaseImageUser
sonar.issue.ignore.multicriteria.dockerBaseImageUser.ruleKey=docker:S6471
sonar.issue.ignore.multicriteria.dockerBaseImageUser.resourceKey=Dockerfile
